# -*- coding: utf-8 -*-
"""Data_Vortex_Phase1_Cleaning_EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHgmarfU6qIcBPJkTYzJU2D-Am6TfgMp

## STEP 1 — Load raw data ✅
"""

import pandas as pd
import numpy as np

# Load the raw corrupted Posts dataset
posts = pd.read_csv('/Social_Engine_Posts_Corrupted.csv')

posts.shape

"""##STEP 2 — Create raw-data audit✅
Before cleaning the dataset, we first inspect its structure, columns, data types, and sample records.

This helps us understand the raw dataset and identify potential data-quality issues before making any changes.
"""

# Display the first 5 rows of the raw dataset
# This gives us an initial look at the structure and values.
posts.head()

# Display all column names in the dataset
# This confirms which fields are available for analysis and cleaning.
posts.columns.tolist()

# Display the number of rows and columns
# Expected output: 12,360 rows and 8 columns.
print("Number of rows:", posts.shape[0])
print("Number of columns:", posts.shape[1])

# Display column data types and the number of non-null values.
# This helps identify columns that may contain missing values
# and columns whose data type may need to be corrected later.
posts.info()

# Generate summary statistics for numerical columns.
# This helps us identify unusual values such as negative likes,
# unexpectedly large values, or unusual distributions.
posts.describe()

# Display the last 5 rows of the raw dataset.
# This helps confirm that the dataset was loaded completely
# and that the final records are not truncated.
posts.tail()

"""### 2A. Duplicate Record Check

We check for duplicate rows and duplicate post IDs without modifying the raw dataset.

Duplicate records can lead to over-counting during analysis and may indicate data corruption.
"""

# Check for completely identical rows
exact_duplicates = posts.duplicated().sum()

print("Exact duplicate rows:", exact_duplicates)

# Check whether any post IDs occur more than once
duplicate_post_ids = posts['post_id'].duplicated().sum()

print("Rows with duplicate post IDs:", duplicate_post_ids)

# Display post IDs that occur more than once
duplicate_id_values = posts.loc[
    posts['post_id'].duplicated(keep=False),
    'post_id'
].value_counts()

duplicate_id_values.head(20)

"""### 2B. Categorical Value Check

We inspect categorical columns to identify their unique values and their frequencies.

This helps us detect unexpected categories, spelling variations, inconsistent capitalization, or other values that may indicate data corruption.
"""

# Display the unique platform values and their frequencies.
# dropna=False ensures that missing platform values are also counted.
platform_values = posts['platform'].value_counts(dropna=False)

print("Platform values and their frequencies:")
print(platform_values)

# Count the number of distinct platform values, excluding missing values.
print("\nNumber of unique platforms:", posts['platform'].nunique())

"""### 2C. ID Format and Integrity Check

We inspect the post and user identifiers to ensure that they are present,
consistently formatted, and suitable for linking the Posts dataset with
the Users dataset.

No values are modified during this audit.
"""

# Check for missing IDs
print("Missing post_id values:", posts['post_id'].isna().sum())
print("Missing user_id values:", posts['user_id'].isna().sum())

# Check the number of unique IDs
print("Unique post_id values:", posts['post_id'].nunique())
print("Unique user_id values:", posts['user_id'].nunique())

# Display a few sample IDs to check their structure
print("Sample post IDs:")
print(posts['post_id'].head(10).tolist())

print("\nSample user IDs:")
print(posts['user_id'].head(10).tolist())

# Check whether any post_id or user_id contains leading/trailing whitespace
post_id_whitespace = posts['post_id'].astype(str).str.strip().ne(posts['post_id'].astype(str)).sum()
user_id_whitespace = posts['user_id'].astype(str).str.strip().ne(posts['user_id'].astype(str)).sum()

print("post_id values with leading/trailing whitespace:", post_id_whitespace)
print("user_id values with leading/trailing whitespace:", user_id_whitespace)

"""###STEP 2D — Timestamp-format audit
The timestamp column may contain dates represented in different formats.

We inspect the raw values to identify the different timestamp formats,
invalid values, and the overall date range before applying any standardisation.
"""

# Display a sample of the raw timestamp values
# This helps us visually identify the formats present in the dataset.
posts['timestamp'].head(20)

# Check how many timestamps appear to be numeric Unix timestamps.
# Unix timestamps are typically represented as numbers such as 1722528840.
numeric_timestamp = pd.to_numeric(posts['timestamp'], errors='coerce')

print("Numeric/Unix-style timestamps:", numeric_timestamp.notna().sum())
print("Non-numeric timestamp values:", numeric_timestamp.isna().sum())

# Temporarily convert timestamps to datetime for auditing.
# The original timestamp column remains unchanged.
parsed_timestamp = pd.to_datetime(
    posts['timestamp'],
    errors='coerce',
    dayfirst=True
)

print("Earliest parsed timestamp:", parsed_timestamp.min())
print("Latest parsed timestamp:", parsed_timestamp.max())
print("Values that could not be parsed:", parsed_timestamp.isna().sum())

# Classify timestamps based on their raw format.
# We are only auditing the data here; the original column is not modified.

timestamp_text = posts['timestamp'].astype(str).str.strip()

# Unix timestamps: digits only
unix_mask = timestamp_text.str.fullmatch(r'\d+')

# ISO-style timestamps: YYYY-MM-DD followed by time
iso_mask = timestamp_text.str.fullmatch(
    r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}'
)

# Date-only values in DD-MM-YYYY format
date_mask = timestamp_text.str.fullmatch(r'\d{2}-\d{2}-\d{4}')

# Anything that does not match the three known patterns
other_mask = ~(unix_mask | iso_mask | date_mask)

print("Unix-style timestamps:", unix_mask.sum())
print("ISO-style timestamps:", iso_mask.sum())
print("DD-MM-YYYY timestamps:", date_mask.sum())
print("Other/unrecognised formats:", other_mask.sum())

"""######**Timestamp inconsistency:** The timestamp column contains three valid representations—Unix timestamp, ISO datetime, and DD-MM-YYYY. All records match one of these formats. This is a standardisation issue rather than missing or unparseable data.

### 2E. Text Content Sanity Check

We inspect the text content for missing or placeholder values, HTML artifacts,
encoding issues, and unusual whitespace.

These observations will guide the text-cleaning process in Step 7.
No text values are modified during this audit.
"""

# Count missing values and empty/whitespace-only text entries
missing_text = posts['text_content'].isna().sum()

empty_text = (
    posts['text_content']
    .fillna('')
    .astype(str)
    .str.strip()
    .eq('')
    .sum()
)

print("Missing text values:", missing_text)
print("Empty/whitespace-only text values:", empty_text)

# Display the most common text values.
# This helps identify placeholders such as NULL or N/A.
posts['text_content'].value_counts(dropna=False).head(20)

# Check for common HTML tags or encoded HTML entities.
text = posts['text_content'].fillna('').astype(str)

html_tag_count = text.str.contains(r'<[^>]+>', regex=True).sum()
html_entity_count = text.str.contains(r'&[a-zA-Z]+;', regex=True).sum()

print("Rows containing HTML-like tags:", html_tag_count)
print("Rows containing HTML entities:", html_entity_count)

# Check for leading/trailing whitespace and embedded line breaks.
whitespace_count = (
    posts['text_content']
    .fillna('')
    .astype(str)
    .ne(posts['text_content'].fillna('').astype(str).str.strip())
    .sum()
)

linebreak_count = (
    posts['text_content']
    .fillna('')
    .astype(str)
    .str.contains(r'[\r\n]', regex=True)
    .sum()
)

print("Rows with leading/trailing whitespace:", whitespace_count)
print("Rows containing line breaks:", linebreak_count)

"""##STEP 3 — Handle exact duplicates✅
Duplicate records can cause posts to be counted more than once during analysis.

We identify completely identical rows and remove only the redundant copies.
The original raw dataset is preserved, while cleaning is performed on a working copy.
"""

# Create a separate working copy of the raw dataset.
# The original 'posts' DataFrame will remain unchanged.
posts_clean = posts.copy()

print("Rows before duplicate removal:", len(posts_clean))

# Count rows that are exact duplicates of an earlier row.
# keep='first' means the first occurrence is treated as the original
# and subsequent identical rows are considered duplicates.
exact_duplicates = posts_clean.duplicated(keep='first').sum()

print("Exact duplicate rows found:", exact_duplicates)

# Remove exact duplicate rows while keeping the first occurrence.
posts_clean = posts_clean.drop_duplicates(keep='first').reset_index(drop=True)

print("Rows after duplicate removal:", len(posts_clean))
print("Rows removed:", len(posts) - len(posts_clean))

# Confirm that no exact duplicate rows remain.
remaining_duplicates = posts_clean.duplicated().sum()

print("Remaining exact duplicate rows:", remaining_duplicates)

"""## STEP 4 — Standardise Timestamps✅

The timestamp column contains three valid representations:
1. Unix timestamps
2. ISO datetime strings
3. DD-MM-YYYY date strings

We convert all three formats into a single datetime format while preserving
the original chronological information.
"""

# Create a copy of the timestamp column for conversion.
# The raw timestamp column remains unchanged until we verify the conversion.
timestamp_raw = posts_clean['timestamp'].astype(str).str.strip()

# Identify Unix-style timestamps (digits only).
unix_mask = timestamp_raw.str.fullmatch(r'\d+')

# Create an empty datetime Series.
standard_timestamp = pd.Series(pd.NaT, index=posts_clean.index)

# Convert Unix timestamps to datetime.
standard_timestamp.loc[unix_mask] = pd.to_datetime(
    timestamp_raw.loc[unix_mask].astype('int64'),
    unit='s',
    errors='coerce'
)

# Convert ISO datetime values.
iso_mask = timestamp_raw.str.fullmatch(
    r'\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}'
)

standard_timestamp.loc[iso_mask] = pd.to_datetime(
    timestamp_raw.loc[iso_mask],
    errors='coerce'
)

# Convert DD-MM-YYYY values.
date_mask = timestamp_raw.str.fullmatch(r'\d{2}-\d{2}-\d{4}')

standard_timestamp.loc[date_mask] = pd.to_datetime(
    timestamp_raw.loc[date_mask],
    format='%d-%m-%Y',
    errors='coerce'
)

# Add the standardised timestamps to the working dataset.
posts_clean['timestamp'] = standard_timestamp

print("Unconverted timestamps:", posts_clean['timestamp'].isna().sum())

# Verify the final timestamp range after standardisation.
print("Earliest timestamp:", posts_clean['timestamp'].min())
print("Latest timestamp:", posts_clean['timestamp'].max())

# Confirm the timestamp column is now stored as a datetime type.
print("Timestamp data type:", posts_clean['timestamp'].dtype)

"""## STEP 5 — Investigate Missing Values✅

We identify missing values in the cleaned working dataset and measure their
frequency and percentage.

The missing values are investigated before deciding whether they can be
recovered, replaced, or should remain missing.
"""

# Count missing values in every column.
missing_count = posts_clean.isna().sum()

# Calculate the percentage of missing values in every column.
missing_percentage = (missing_count / len(posts_clean)) * 100

# Create a summary table for easier interpretation.
missing_summary = pd.DataFrame({
    'Missing Values': missing_count,
    'Missing Percentage': missing_percentage.round(2)
})

# Display only columns that contain missing values.
missing_summary[missing_summary['Missing Values'] > 0]

# Count how many rows have different numbers of missing fields.
# This helps us understand whether missing values are concentrated
# in the same records or spread across different records.

missing_per_row = posts_clean.isna().sum(axis=1)

print("Rows with no missing values:", (missing_per_row == 0).sum())
print("Rows with 1 missing value:", (missing_per_row == 1).sum())
print("Rows with 2 missing values:", (missing_per_row == 2).sum())
print("Rows with 3 missing values:", (missing_per_row == 3).sum())

# Display a sample of rows containing at least one missing value.
# We inspect the surrounding information before deciding how to handle them.

posts_clean[posts_clean.isna().any(axis=1)].head(20)

# Display a few complete examples from each column containing missing values.
# This helps us understand whether the missing data appears random or follows
# an identifiable pattern.

for column in ['platform', 'text_content', 'likes']:
    print(f"\n--- {column} ---")
    print(posts_clean[posts_clean[column].isna()].head(5))

"""### 5A. Investigating Missing Platform Values

We examine posts with missing platform information to determine whether the
platform can be reliably recovered from other available fields.

Platform values will only be reconstructed when sufficient evidence exists.
Otherwise, the missing value will be retained rather than guessed.
"""

# Select rows where the platform value is missing.
missing_platform = posts_clean[posts_clean['platform'].isna()]

# Display a sample of posts with missing platform information.
missing_platform[
    ['post_id', 'user_id', 'text_content', 'timestamp', 'likes', 'shares', 'comments']
].head(20)

# Look for explicit social-media platform names inside the text content.
# This is only an investigation; no values are changed.

platform_keywords = r'Facebook|Instagram|Twitter|YouTube|Reddit|LinkedIn|TikTok'

platform_mentions = missing_platform['text_content'].fillna('').str.contains(
    platform_keywords,
    case=False,
    regex=True
)

print("Missing-platform rows mentioning a platform:", platform_mentions.sum())
print("Total missing-platform rows:", len(missing_platform))

"""### 5B. Investigating Missing Text Content

We examine records with missing text content to determine whether the
information can be recovered from other fields.

Text will not be fabricated or inferred from unrelated metadata.
"""

# Select rows where text content is missing.
missing_text = posts_clean[posts_clean['text_content'].isna()]

# Display a sample of records with missing text.
missing_text[
    ['post_id', 'user_id', 'platform', 'timestamp', 'likes', 'shares', 'comments']
].head(20)

# Check whether any missing-text post IDs have another record
# containing the same post ID.
text_recovery_check = posts_clean[
    posts_clean['post_id'].isin(missing_text['post_id'])
]

print("Total records matching missing-text post IDs:",
      len(text_recovery_check))

print("Unique missing-text post IDs:",
      missing_text['post_id'].nunique())

"""### 5C. Investigating Missing Likes

We examine records with missing likes to determine whether the missing
engagement value can be recovered from another occurrence of the same post.

Likes will not be estimated from shares, comments, or other unrelated fields.
"""

# Select rows where likes are missing.
missing_likes = posts_clean[posts_clean['likes'].isna()]

print("Rows with missing likes:", len(missing_likes))
print("Unique post IDs with missing likes:", missing_likes['post_id'].nunique())

# Check whether any missing-like post IDs occur elsewhere in the dataset.
# If another record with the same post_id has a valid likes value,
# that value could potentially be used for recovery.

likes_recovery_check = posts_clean[
    posts_clean['post_id'].isin(missing_likes['post_id'])
]

print("Records matching missing-like post IDs:",
      len(likes_recovery_check))

# Check whether any of the matching post IDs have a non-missing likes value.
recoverable_likes = likes_recovery_check[
    likes_recovery_check['likes'].notna()
]

print("Missing-like records with another valid likes value:",
      len(recoverable_likes))

"""## STEP 6 — Fix Invalid Numerical Values✅

We inspect numerical engagement fields for values that violate logical
constraints.

Likes, shares, and comments represent counts of user interactions and
therefore cannot be negative.

Invalid values are identified first and will only be corrected after
their extent and pattern have been investigated.

### 6A. Identify Invalid Numerical Values

We examine the numerical engagement fields for values that violate
logical constraints.

Since likes, shares, and comments represent counts of interactions,
negative values are considered invalid. We first quantify these values
before applying any correction.
"""

# Define the numerical engagement columns to audit.
numeric_columns = ['likes', 'shares', 'comments']

# Count negative values in each engagement column.
negative_summary = {}

for column in numeric_columns:
    negative_summary[column] = (posts_clean[column] < 0).sum()

print("Negative values by column:")
print(negative_summary)

# Display rows containing negative likes.
# We inspect the surrounding information before deciding how to correct them.

negative_likes = posts_clean[posts_clean['likes'] < 0]

negative_likes[
    ['post_id', 'user_id', 'platform', 'text_content',
     'timestamp', 'likes', 'shares', 'comments']
].head(20)

# Summarise the invalid likes values.
# This shows how extreme the negative values are.

print("Number of negative likes:", len(negative_likes))
print("Minimum likes value:", negative_likes['likes'].min())
print("Maximum negative likes value:", negative_likes['likes'].max())

# Check the minimum values of all numerical engagement fields.
# This confirms whether negative values occur only in likes
# or also appear in shares and comments.

for column in numeric_columns:
    print(f"{column}: minimum = {posts_clean[column].min()}")

"""### 6B. Investigate Negative Likes for Possible Recovery

Negative values were found only in the likes column. Before replacing
these values, we check whether the affected posts appear elsewhere in
the dataset with a valid likes value.

If a valid value exists for the same post_id, it may provide a reliable
way to recover the corrupted value. If no such value exists, we will
treat the negative value as invalid rather than guessing its intended
value.
"""

# Check whether any post IDs with negative likes appear elsewhere
# with a valid (non-negative) likes value.

negative_post_ids = negative_likes['post_id']

negative_like_recovery = posts_clean[
    posts_clean['post_id'].isin(negative_post_ids) &
    (posts_clean['likes'] >= 0)
]

print(
    "Negative-like records with another valid likes value:",
    len(negative_like_recovery)
)

"""### 6C. Assess Relationship with Other Engagement Metrics

We examine the statistical relationship between likes, shares, and comments
to determine whether other engagement metrics provide evidence for recovering
invalid likes values.

This analysis is exploratory. Correlation is not used to fabricate or directly
replace individual likes values.
"""

# Calculate the pairwise correlation between engagement metrics.
# This is used only to understand relationships within the dataset.

engagement_correlation = posts_clean[
    ['likes', 'shares', 'comments']
].corr()

engagement_correlation

"""### 6D. Correct Invalid Likes Values

The negative likes values cannot be reliably recovered from the available
data. Since negative engagement counts are invalid, these values are
converted to missing values (NaN).

This preserves data integrity by explicitly representing the true likes
count as unknown rather than introducing an estimated or fabricated value.
"""

# Count negative likes before correction.
negative_before = (posts_clean['likes'] < 0).sum()

# Replace negative likes with NaN because their true values cannot
# be reliably recovered from the available dataset.
posts_clean.loc[posts_clean['likes'] < 0, 'likes'] = np.nan

# Verify the correction.
negative_after = (posts_clean['likes'] < 0).sum()

print("Negative likes before correction:", negative_before)
print("Negative likes after correction:", negative_after)
print("Missing likes after correction:", posts_clean['likes'].isna().sum())

"""### 6E. Final Numerical Validation

We verify that all engagement values remaining in the cleaned dataset satisfy
the basic logical constraint that valid engagement counts cannot be negative.

Missing values are allowed because they represent unavailable information.
"""

# Verify that no negative engagement values remain.
# Missing values (NaN) are excluded from the comparison.

for column in ['likes', 'shares', 'comments']:
    negative_count = (posts_clean[column] < 0).sum()
    print(f"{column} - negative values remaining: {negative_count}")

# Display the minimum valid value for each engagement metric.
print("\nMinimum valid values:")
print(posts_clean[['likes', 'shares', 'comments']].min())

"""## STEP 7 — Clean Text / HTML Artifacts✅

The text_content column is inspected for HTML tags, HTML entities,
leading/trailing whitespace, and line breaks.

These formatting artifacts are removed or standardised while preserving
the original textual meaning. Missing text values are left unchanged.
"""

# Create a copy of the text column before cleaning.
# This allows the original cleaned-dataset state to be compared if needed.

text_before = posts_clean['text_content'].copy()

import re
import html

# Define a function to clean HTML-related artifacts from text.
def clean_text(text):
    # Leave missing text values unchanged.
    if pd.isna(text):
        return text

    # Convert the value to a string.
    text = str(text)

    # Remove HTML tags such as <br>, <p>, <div>, etc.
    text = re.sub(r'<[^>]+>', ' ', text)

    # Decode HTML entities such as &amp;, &lt;, &gt;, etc.
    text = html.unescape(text)

    # Replace line breaks and tabs with a single space.
    text = re.sub(r'[\r\n\t]+', ' ', text)

    # Remove unnecessary repeated whitespace.
    text = re.sub(r'\s+', ' ', text)

    # Remove leading and trailing whitespace.
    text = text.strip()

    return text


# Apply the cleaning function to the text_content column.
posts_clean['text_content'] = posts_clean['text_content'].apply(clean_text)

# Check whether HTML-like tags remain after cleaning.
remaining_html_tags = posts_clean['text_content'].fillna('').str.contains(
    r'<[^>]+>',
    regex=True
).sum()

# Check whether common HTML entities remain.
remaining_html_entities = posts_clean['text_content'].fillna('').str.contains(
    r'&(?:amp|lt|gt|quot|apos|nbsp);',
    regex=True,
    case=False
).sum()

# Check whether line breaks remain.
remaining_line_breaks = posts_clean['text_content'].fillna('').str.contains(
    r'[\r\n\t]',
    regex=True
).sum()

print("HTML-like tags remaining:", remaining_html_tags)
print("HTML entities remaining:", remaining_html_entities)
print("Line breaks remaining:", remaining_line_breaks)

# Check for leading or trailing whitespace in non-missing text values.
whitespace_issues = posts_clean['text_content'].dropna().apply(
    lambda x: x != x.strip()
).sum()

print("Rows with leading/trailing whitespace remaining:", whitespace_issues)

"""## STEP 8 — Validate Against Users Dataset✅

The Posts dataset contains a user_id field that should correspond to a
valid user in the Users dataset.

We cross-check the user_id values between both datasets to identify posts
that reference users who are not present in the Users table.
"""

# Load the Users dataset for cross-validation.
users = pd.read_csv('/Social_Engine_Users.csv')

# Display the dimensions of the Users dataset.
print("Users dataset shape:", users.shape)

# Display the column names.
print("\nUsers dataset columns:")
print(users.columns.tolist())

"""### Check Users Dataset User IDs

The Users dataset is used as the reference table for validating post
ownership. We first verify that its user_id values are complete and unique.
"""

# Check for missing user IDs in the Users dataset.
print("Missing user_id values:", users['user_id'].isna().sum())

# Check for duplicate user IDs.
print("Duplicate user_id values:", users['user_id'].duplicated().sum())

# Count unique user IDs.
print("Unique user_id values:", users['user_id'].nunique())

# Count total user records.
print("Total user records:", len(users))

# Create a set of valid user IDs from the Users dataset.
valid_user_ids = set(users['user_id'])

# Identify posts whose user_id does not exist in the Users dataset.
invalid_user_posts = posts_clean[
    ~posts_clean['user_id'].isin(valid_user_ids)
]

print("Posts with user_id not found in Users dataset:",
      len(invalid_user_posts))

print("Unique invalid user_ids:",
      invalid_user_posts['user_id'].nunique())

"""### Check User–Post Coverage

We compare the Users and Posts datasets to determine how many registered
users have at least one post and how many users have no associated posts.

Users without posts are not automatically treated as invalid because an
inactive user may legitimately have no post records.
"""

# Count the number of posts associated with each user.
posts_per_user = posts_clean.groupby('user_id').size()

# Identify users from the Users dataset who have no posts.
users_without_posts = users[
    ~users['user_id'].isin(posts_per_user.index)
]

# Display the coverage results.
print("Total users:", len(users))
print("Users with at least one post:", len(posts_per_user))
print("Users without posts:", len(users_without_posts))

# Show the distribution of the number of posts per user.
# This helps identify whether posts are concentrated among a small number
# of users or distributed across the user population.

posts_per_user.describe()

"""## STEP 9 — Final Quality Checks✅

The cleaned Posts dataset is subjected to final consistency and integrity
checks before export.

The checks verify that duplicate records have been removed, numerical
constraints are satisfied, timestamps are valid, text artifacts have been
cleaned, missing values are documented, and all user references remain
valid.
"""

# Check the final number of rows and columns.
print("Final dataset shape:", posts_clean.shape)

# Check for remaining exact duplicate rows.
print("Exact duplicate rows:", posts_clean.duplicated().sum())

# Check for duplicate post IDs.
print("Duplicate post IDs:", posts_clean['post_id'].duplicated().sum())

# Check the final missing-value counts after all cleaning operations.
# These values are reported rather than automatically filled because
# the original information could not be reliably recovered.

final_missing = posts_clean.isna().sum()

final_missing_summary = pd.DataFrame({
    'Missing Values': final_missing,
    'Missing Percentage': (
        final_missing / len(posts_clean) * 100
    ).round(2)
})

final_missing_summary[final_missing_summary['Missing Values'] > 0]

# Check that no negative engagement values remain.

for column in ['likes', 'shares', 'comments']:
    negative_count = (posts_clean[column] < 0).sum()
    print(f"{column} - negative values remaining: {negative_count}")

# Display the minimum valid value in each engagement column.
print("\nMinimum valid values:")
print(posts_clean[['likes', 'shares', 'comments']].min())

# Check the timestamp data type.
print("Timestamp data type:", posts_clean['timestamp'].dtype)

# Count any missing timestamps after standardisation.
print("Missing timestamps:", posts_clean['timestamp'].isna().sum())

# Check the final timestamp range.
print("Earliest timestamp:", posts_clean['timestamp'].min())
print("Latest timestamp:", posts_clean['timestamp'].max())

# Check for remaining HTML-like tags.
remaining_html_tags = posts_clean['text_content'].fillna('').str.contains(
    r'<[^>]+>',
    regex=True
).sum()

# Check for remaining common HTML entities.
remaining_html_entities = posts_clean['text_content'].fillna('').str.contains(
    r'&(?:amp|lt|gt|quot|apos|nbsp);',
    regex=True,
    case=False
).sum()

# Check for remaining line breaks or tabs.
remaining_line_breaks = posts_clean['text_content'].fillna('').str.contains(
    r'[\r\n\t]',
    regex=True
).sum()

# Check that every user_id exists in the Users dataset.
invalid_user_ids = (~posts_clean['user_id'].isin(valid_user_ids)).sum()

print("HTML-like tags remaining:", remaining_html_tags)
print("HTML entities remaining:", remaining_html_entities)
print("Line breaks/tabs remaining:", remaining_line_breaks)
print("Invalid user_id values:", invalid_user_ids)

# Display the final column names and data types.
print("Final columns:")
print(posts_clean.columns.tolist())

print("\nFinal data types:")
print(posts_clean.dtypes)

# Verify that the expected 8 columns are present.
expected_columns = [
    'post_id',
    'user_id',
    'platform',
    'text_content',
    'timestamp',
    'likes',
    'shares',
    'comments'
]

missing_columns = set(expected_columns) - set(posts_clean.columns)
unexpected_columns = set(posts_clean.columns) - set(expected_columns)

print("\nMissing expected columns:", missing_columns)
print("Unexpected columns:", unexpected_columns)

# Verify important data types.
print("\nData-type checks:")
print("post_id is object:", posts_clean['post_id'].dtype == 'object')
print("user_id is object:", posts_clean['user_id'].dtype == 'object')
print("timestamp is datetime:", pd.api.types.is_datetime64_any_dtype(posts_clean['timestamp']))
print("likes is numeric:", pd.api.types.is_numeric_dtype(posts_clean['likes']))
print("shares is numeric:", pd.api.types.is_numeric_dtype(posts_clean['shares']))
print("comments is numeric:", pd.api.types.is_numeric_dtype(posts_clean['comments']))

"""## STEP 10 — Export Cleaned Dataset✅

The validated and cleaned Posts dataset is exported as a CSV file for
submission.

Missing values are retained as empty CSV fields because their original
values could not be reliably recovered. No data is fabricated during export.
"""

# Export the final cleaned Posts dataset to CSV.
# NaN values are written as empty fields in the CSV.

output_file = 'Social_Engine_Posts_Cleaned.csv'

posts_clean.to_csv(
    output_file,
    index=False
)

print("Cleaned dataset exported successfully.")
print("File:", output_file)
print("Rows:", len(posts_clean))
print("Columns:", len(posts_clean.columns))

# Reload the exported CSV file.
posts_final = pd.read_csv('Social_Engine_Posts_Cleaned.csv')

# Check the saved dataset dimensions.
print("Reloaded dataset shape:", posts_final.shape)

# Check the column names.
print("\nReloaded columns:")
print(posts_final.columns.tolist())

# Check for exact duplicate rows after export.
print("\nExact duplicate rows:", posts_final.duplicated().sum())

# Check for duplicate post IDs.
print("Duplicate post IDs:", posts_final['post_id'].duplicated().sum())

# Check for negative engagement values after export.
print("\nNegative engagement values:")
for column in ['likes', 'shares', 'comments']:
    print(f"{column}:", (posts_final[column] < 0).sum())

# Check missing values after export.
print("\nMissing values:")
print(posts_final.isna().sum())

from google.colab import files

files.download('Social_Engine_Posts_Cleaned.csv')